export enum CacheEnum {
  TOKEN_KEY = 'TOKEN_KEY',
  ACCOUNT_INFO_KEY = 'ACCOUNT_INFO_KEY',
  USER_INFO_KEY = 'USER_INFO_KEY',
  MENU_LIST_KEY = 'MENU_LIST_KEY',
  THEME_KEY = 'THEME_KEY',
  APP_MODE_THEME_KEY = 'APP_MODE_THEME_KEY',
  APP_PROJECT_SETTING_KEY = 'APP_PROJECT_SETTING_KEY'
}
